on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install node v16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Debug
        run: |
          pwd
          ls -R
      - name: npm install
        run: npm install
        working-directory: ./api
      - name: tsc
        uses: icrawl/action-tsc@v1
  # test job goes here
