on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install node v16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: npm install
        run: npm install
        working-directory: ./api
      - name: Install TypeScript
        run: npm install -g typescript
      - name: tsc
        run: tsc --noEmit --noErrorTruncation --pretty false --incremental false
