on:
  pull_request:
    branches:
      - main
      - dev

  push:
    branches:
      - main
      - dev

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Debug
        run: |
          pwd
          ls -R
      - name: Install Dependencies
        run: npm ci
        working-directory: ./api
      - name: Compile TypeScript
        run: npm run build
        working-directory: ./api

  run-tests:
    name: Run Tests in user-service
    needs: tsc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Debug
        run: |
          pwd
          ls -R
      - name: Install Dependencies
        run: npm ci
        working-directory: ./user-service
      - name: Run Tests
        env:
          JWT_SECRET: $({ secrets.JWT_SECRET })
        run: npm test
        working-directory: ./user-service
